#!/bin/bash

for OPT in "$@"
do
  case "$OPT" in
    '-c'|'--compile')
      onlycompile=1
      shift
      ;;
    '-p')
      compiler=g++
      shift
      ;;
    '--'|'-' )
      shift 1
      param+=( "$@" )
      break
      ;;
    -*)
      echo "$PROGNAME: 「$(echo $1 | sed 's/^-*//')」オプションは存在しません．" 1>&2
      exit 1
      ;;
    *)
      if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
        param+=( "$1" )
        shift 1
      fi
      ;;
  esac
done

bfname=`basename $param`
bdir=`dirname $param`
filename=$bdir/$bfname
execfile=$bdir/${bfname%.*}

if [ -z  "$compiler" ]; then
  case "$bfname" in
    *\.cpp)
      compiler=g++
      ;;
    *)
      compiler=gcc
      ;;
  esac
fi

$compiler -o $execfile $filename

if [ -z "$onlycompile" ] && [ $? = 0 ] ; then
  $execfile ${param[@]:1:(${#param[@]}-1)}
  rm $execfile
fi

