#!/bin/bash

# Option parsing template by http://qiita.com/rita_cano_bika/items/9fcb2a61c6f360632541
PROGNAME=$(basename $0)
LATEX_BIN=uplatex

function update_latex_bin () {
  if [ -x `which $1` -o -x "$1" ] ; then
    LATEX_BIN=$1
  else
    echo "$1 が存在しません．" 1>&2
  fi
}

for OPT in "$@"
do
  case "$OPT" in
    '-o'|'--open' )
      open=1
      shift
      ;;
    '-d'|'--directory'|'-D')
      if [[ "$1" = "-D" ]]; then
        pdfsamedir=1
      fi
      chdst=1
      if [[ ! -z "$2" ]] && [[ ! "$2" =~ ^-+ ]]; then
        dstdir="$2"
        shift
      fi
      shift
      ;;
    '--detect')
      autodetect=1
      shift
      ;;
    '-t')
      pdfsamedir=1
      chdst=1
      dstdirname=texfiles
      shift
      ;;
    '-p')
      if [[ ! -z "$2" ]]; then
        pdfbasename="$2"
      else
        echo "$PROGNAME: p オプションには引数が必要です．" 1>&2
        exit 1
      fi
      shift 2
      ;;
    '-r'|'--remove')
      texfilesdelete=1
      shift
      ;;
    '--platex')
      update_latex_bin platex
      shift
      ;;
    '--uplatex')
      update_latex_bin uplatex
      shift
      ;;
    '--'|'-' )
      shift 1
      param+=( "$@" )
      break
      ;;
    -*)
      echo "$PROGNAME: 「$(echo $1 | sed 's/^-*//')」オプションは存在しません．" 1>&2
      exit 1
      ;;
    *)
      if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
        param+=( "$1" )
        shift 1
      fi
      ;;
  esac
done

if [ -z $param ]; then
  echo "$PROGNAME: 引数がありません．"
  exit 1
fi
srcbn=$(basename $param)
srcdir=$(dirname $param)
noext=${srcbn%.tex}

if [[ "$chdst" = "1" ]] && [[ -z "$dstdir" ]]; then
  if [[ -z "$dstdirname" ]]; then
    dstdirname=$noext
  fi
  dstdir=$srcdir/$dstdirname
elif [[ ! "$chdst" = "1" ]]; then
  dstdir=.
fi

if [[ "$autodetect" = "1" ]] && [[ -z "$pdffilename" ]]; then
  tmp=$(grep -oE '^%\s*makepdf-filename:\s*.+$' "$param" | \
        ruby -e 'a=/^%\s*makepdf-filename:\s*(.+)/.match(STDIN.gets); puts a[1] if a != nil')
  if [[ "$tmp" = "" ]]; then
    echo "--detect: makepdf-filename: (filename) が記述された行がありません．" 1>&2
    exit 1
  else
    pdfbasename="$tmp"
  fi
fi

if [[ ! -d "$dstdir" ]]; then
  mkdir -p $dstdir
fi

if [[ "$pdfsamedir" = "1" ]]; then
  pdfdir=$srcdir
else
  pdfdir=$dstdir
fi

if [[ -z "$pdfbasename" ]]; then
  pdfbasename=$noext.pdf
fi

pdffn=$pdfdir/$pdfbasename

for f in 1st 2nd 3rd final; do
  echo "---------- $f try ----------"
  result=`$LATEX_BIN -interaction=nonstopmode --output-directory="$dstdir" $param`
  if [ ! $? = 0 ]; then
    echo "$result"
    exit 1
  fi
  grep 'Rerun' "$dstdir/$noext.log" || break
done

dvipdfmx -o $pdffn "$dstdir/$noext.dvi"

if [[ "$texfilesdelete" = "1" ]]; then
  rm -f $dstdir/$noext.{dvi,aux,log}
fi

if [ "$open" = 1 ] ; then
    open $pdffn
fi
