#!/bin/bash

open=0
# Option parsing template by http://qiita.com/rita_cano_bika/items/9fcb2a61c6f360632541
PROGNAME=$(basename $0)
for OPT in "$@"
do
  case "$OPT" in
    '-o'|'--open' )
      open=1
      shift
      ;;
    '-d'|'--directory')
      chdst=1
      if [[ ! -z "$2" ]] && [[ ! "$2" =~ ^-+ ]]; then
        dstdir="$2"
        shift
      fi
      shift
      ;;
    '--'|'-' )
      shift 1
      param+=( "$@" )
      break
      ;;
    -*)
      echo "$PROGNAME: 「$(echo $1 | sed 's/^-*//')」オプションは存在しません．" 1>&2
      exit 1
      ;;
    *)
      if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
        param+=( "$1" )
        shift 1
      fi
      ;;
  esac
done

if [ -z $param ]; then
  echo "$PROGNAME: 引数がありません．"
  exit 1
fi
target=$param

if [[ "$chdst" = "1" ]]; then
  if [[ -z "$dstdir" ]]; then
    dstdir=$(dirname $target)/${target%.tex}
  fi
  dopt="--output-directory=$dstdir"
fi

for f in 1st 2nd 3rd final; do
  echo "---------- $f try ----------"
  uplatex -interaction=nonstopmode $dopt $target > /dev/null || exit 1
  grep 'Rerun' ${target%.tex}.log || break
done

dvipdfmx ${target%.tex}.dvi

if [ "$open" = 1 ] ; then
    open ${1%.tex}.pdf
fi
